STAFF_ROLE_ID = 1487264906012262611
ADMIN_ROLE_ID = 1483933455334248538
OWNER_ROLE_ID = 1487264776517320744
MOD_ROLE_ID = 1487264835732377601

BAN_ALLOWED_ROLES = {
    STAFF_ROLE_ID,
    ADMIN_ROLE_ID,
    OWNER_ROLE_ID,
}

UNBAN_ALLOWED_ROLES = {
    STAFF_ROLE_ID,
    ADMIN_ROLE_ID,
    OWNER_ROLE_ID,
}

KICK_ALLOWED_ROLES = {
    STAFF_ROLE_ID,
    ADMIN_ROLE_ID,
    OWNER_ROLE_ID,
}

MUTE_ALLOWED_ROLES = {
    STAFF_ROLE_ID,
    ADMIN_ROLE_ID,
    OWNER_ROLE_ID,
    MOD_ROLE_ID,
}

UNMUTE_ALLOWED_ROLES = {
    STAFF_ROLE_ID,
    ADMIN_ROLE_ID,
    OWNER_ROLE_ID,
    MOD_ROLE_ID,
}

PURGE_ALLOWED_ROLES = {
    STAFF_ROLE_ID,
    ADMIN_ROLE_ID,
    OWNER_ROLE_ID,
    MOD_ROLE_ID,
}

WARN_ALLOWED_ROLES = {
    STAFF_ROLE_ID,
    ADMIN_ROLE_ID,
    OWNER_ROLE_ID,
    MOD_ROLE_ID,
}

WARNINGS_ALLOWED_ROLES = {
    STAFF_ROLE_ID,
    ADMIN_ROLE_ID,
    OWNER_ROLE_ID,
    MOD_ROLE_ID,
}

DELWARN_ALLOWED_ROLES = {
    STAFF_ROLE_ID,
    ADMIN_ROLE_ID,
    OWNER_ROLE_ID,
    MOD_ROLE_ID,
}

CLEARWARNS_ALLOWED_ROLES = {
    STAFF_ROLE_ID,
    ADMIN_ROLE_ID,
    OWNER_ROLE_ID,
}